package servent.message;

public enum MessageType {
    HAIL,
    CONTACT,
    REJECT,
    SYSTEM_KNOCK,
    WELCOME,
    CONNECTION_REQUEST,
    CONNECTION_RESPONSE,
    ENTER,
    JOIN,
    LEAVE,
    QUIT,
    PURGE,
    STOP_SHARE_JOB,
    STOPPED_JOB_INFO,
    START_JOB_GENESIS,
    APPROACH_CLUSTER,
    CLUSTER_KNOCK,
    CLUSTER_WELCOME,
    CLUSTER_CONNECTION_REQUEST,
    CLUSTER_CONNECTION_RESPONSE,
    ENTERED_CLUSTER
}
