package servent.message;

public enum MessageType {
    HAIL,
    CONTACT,
    REJECT,
    SYSTEM_KNOCK,
    WELCOME,
    CONNECTION_REQUEST,
    CONNECTION_RESPONSE,
    ENTER,
    JOIN,
    LEAVE,
    QUIT,
    PURGE,
    CLUSTER_KNOCK,
    CLUSTER_WELCOME,
    ENTERED_CLUSTER,
    CLUSTER_CONNECTION_REQUEST,
    CLUSTER_CONNECTION_RESPONSE
}
